version: '3.7'
services:
  arangodb_db_container:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: rootpassword
    ports:
      - 8529:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps
  aircraft_db:
    image: aircraft_db:latest
    depends_on:
      - arangodb_db_container
    network_mode: "host"
    environment:
      - ROOT_USER_NAME=root
      - ROOT_USER_PASSWORD=rootpassword
volumes:
  arangodb_data_container:
  arangodb_apps_data_container: